# Docker Compose for Server 1
# App only - connects to external PostgreSQL
# Usage: docker-compose -f deploy/docker-compose.server1.yml up -d

version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: minesweeper-app-server1
    restart: unless-stopped
    env_file:
      - ../.env.server1
    ports:
      - "${PORT:-3030}:3030"
    networks:
      - minesweeper-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3030/api/leaderboard"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  minesweeper-network:
    driver: bridge

